# - - - OK - - -
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
# build = 'make -f make_mac.mak'
# hook_post_update = '''
#   if dein#util#_is_windows()
#     let cmd = 'tools\\update-dll-mingw'
#   elseif dein#util#_is_cygwin()
#     let cmd = 'make -f make_cygwin.mak'
#   elseif dein#util#_is_mac()
#     let cmd = 'make -f make_mac.mak'
#   elseif executable('gmake')
#     let cmd = 'gmake'
#   else
#     let cmd = 'make'
#   endif
#   let g:dein#plugin.build = cmd
# '''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
nmap <Leader>x <plug>NERDCommenterToggle
vmap <Leader>x <plug>NERDCommenterToggle
'''

[[plugins]]
repo = 'vim-scripts/quickhl.vim'
hook_add = '''
let g:quickhl_manual_enable_at_startup = 1
let g:quickhl_manual_keywords = [ "TODO", "CAUTION", "DELETED", "NOTE" ]
nmap <Space>m <Plug>(quickhl-manual-this)
xmap <Space>m <Plug>(quickhl-manual-this)
nmap <Space>M <Plug>(quickhl-manual-reset)
xmap <Space>M <Plug>(quickhl-manual-reset)
nmap <Space>j <Plug>(quickhl-cword-toggle)
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'kana/vim-smartword'

[[plugins]]
repo = 'AndrewRadev/switch.vim'
hook_add = '''
nmap <silent> ,s :<C-u>:Switch<CR>
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size  = 1
'''

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'vim-scripts/Colour-Sampler-Pack'

[[plugins]]
repo = 'tomasr/molokai'

# - - - 途中 - - -

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
nnoremap [unite] <Nop>
nmap ,u [unite]
nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
nnoremap <silent> [unite]f :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> [unite]r :<C-u>Unite -buffer-name=register register<CR>
nnoremap <silent> [unite]m :<C-u>Unite file_mru<CR>
nnoremap <silent> [unite]u :<C-u>Unite buffer file_mru<CR>
nnoremap <silent> [unite]a :<C-u>UniteWithBufferDir -buffer-name=files file buffer file_mru bookmark<CR>
nnoremap <silent> [unite]c :<C-u>Unite bookmark<CR>
nnoremap <silent> [unite]A :<C-u>UniteBookmarkAdd<CR>
'''

# NOTE: ここで定義しにくいので .vimrc に直接書いた
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
# let g:lightline = {
#   "colorscheme": "wombat",
#   "active": {
#     "left": [ [ "mode", "paste" ], [ "fugitive", "filename"] ]
#   },
#   "component_function": {
#     "fugitive": "%{exists(\"*fugitive#head\") && strlen(fugitive#head()) ? \"⭠ \".fugitive#head() : \"\"}",
#     "readonly": "%{&filetype == \"help\" ? \"\" : &readonly ? \"⭤\" : \"\"}",
#     "modified": "%{&filetype == \"help\" ? \"\" : &modified ? \"+\" : \"\"}",
#     "filename": "%{\"HOGE\"}"
#   },
#   "separator": { "left": "⮀", "right": "⮂" },
#   "subseparator": { "left": "⮁", "right": "⮃" }
# }
# '''

# - - - まだ - - -

# lang
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'google/vim-ft-go'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'fatih/vim-go'
