[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make -f make_mac.mak'
# hook_post_update = '''
#   if dein#util#_is_windows()
#     let cmd = 'tools\\update-dll-mingw'
#   elseif dein#util#_is_cygwin()
#     let cmd = 'make -f make_cygwin.mak'
#   elseif dein#util#_is_mac()
#     let cmd = 'make -f make_mac.mak'
#   elseif executable('gmake')
#     let cmd = 'gmake'
#   else
#     let cmd = 'make'
#   endif
#   let g:dein#plugin.build = cmd
# '''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
'''

[[plugins]]
repo = 'vim-scripts/quickhl.vim'
hook_add = '''
let g:quickhl_manual_enable_at_startup = 1
let g:quickhl_manual_keywords = [ "TODO", "CAUTION", "DELETED" ]
nmap <Leader>x <plug>NERDCommenterToggle
vmap <Leader>x <plug>NERDCommenterToggle
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'kana/vim-smartword'


# - - - OK - - -

# [[plugins]]
# repo = 'Shougo/unite.vim'

# [[plugins]] # awesome status line
# repo = 'itchyny/lightline.vim'
# hook_source = '''
#   let g:lightline = {
#     'colorscheme': 'landscape',
#   }
# '''
# hook_add = '''
#  let g:lightline = {
#    'colorscheme': 'wombat',
#    'active': {
#      'left': [ [ 'mode', 'paste' ],
#                [ 'fugitive', 'filename'] ]
#    },
#    'component_function': {
#      'fugitive': 'MyFugitive',
#      # 'readonly': 'MyReadonly',
#      'readonly': '%{&filetype == "help" ? "" : &readonly ? "⭤" : ""}'
#
#      'modified': 'MyModified',
#      'filename': 'MyFilename'
#    },
#    'separator': { 'left': '⮀', 'right': '⮂' },
#    'subseparator': { 'left': '⮁', 'right': '⮃' }
#  }
# '''

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'google/vim-ft-go'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'fatih/vim-go'
