[[plugins]]
repo = 'rking/ag.vim'
on_cmd = ['Ag']

# filetyps {{{
# toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
# }}}

# coffee {{{
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']
# }}}

# haml {{{
[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']
# }}}

# dockerfile {{{
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']
# }}}

# golang {{{
[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = ['go']
# }}}

# }}}

# [[plugins]]
# repo = 'scrooloose/nerdcommenter'
# on_map = [['n', '<Plug>']]
# on_map = ['<Plug>NERDCommenterToggle']
# hook_add = '''
#   nmap <Leader>x <Plug>NERDCommenterToggle
#   vmap <Leader>x <Plug>NERDCommenterToggle
# '''
# hook_source = '''
#   let g:NERDSpaceDelims = 1
# '''

# vim: foldmethod=marker
