[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'rking/ag.vim'
on_cmd = ['Ag']

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

# [[plugins]]
# repo = 'scrooloose/nerdcommenter'
# on_map = [['n', '<Plug>']]
# on_map = ['<Plug>NERDCommenterToggle']
# hook_add = '''
#   nmap <Leader>x <Plug>NERDCommenterToggle
#   vmap <Leader>x <Plug>NERDCommenterToggle
# '''
# hook_source = '''
#   let g:NERDSpaceDelims = 1
# '''
